name: Publish to GitHub Packages
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: https://npm.pkg.github.com
                  scope: '@honsali'
                  always-auth: true

            - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
            - run: yarn install
            - run: yarn publish --access public --verbose --registry=https://npm.pkg.github.com
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
